name: CI/CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

concurrency:
  group: deploy-prod
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      # Compute normalized (lowercase) image name and short SHA as step outputs
      - name: Compute image meta
        id: meta
        shell: bash
        run: |
          echo "image=ghcr.io/${GITHUB_REPOSITORY,,}" >> "$GITHUB_OUTPUT"
          echo "short_sha=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Show image tag
        run: echo "Will build and push -> ${{ steps.meta.outputs.image }}:latest (${{ steps.meta.outputs.short_sha }})"

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          docker build \
            -t "${{ steps.meta.outputs.image }}:latest" \
            -t "${{ steps.meta.outputs.image }}:sha-${{ steps.meta.outputs.short_sha }}" \
            .

      - name: Push images
        run: |
          docker push "${{ steps.meta.outputs.image }}:latest"
          docker push "${{ steps.meta.outputs.image }}:sha-${{ steps.meta.outputs.short_sha }}"

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: SSH pull & restart
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            set -e
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin || true

            cd /server/ai2/html/calculator-node
            docker compose pull
            docker compose up -d
            docker image prune -f
